### PR TITLE
feat(docker): create lacchain local image

### PR DESCRIPTION
**Pull request by leisterfrancisco**
Create image to run lacchain locally

**Steps to test**:
1. docker build -t lacchain-image .
2. docker run -dp 3000:8888 lacchain-image

### CODE REVIEW

**Comment by xavier506** [comment]
@leisterfrancisco  this looks great!

Why do you run on port 3000? I would think port 8888 is better as cleos is configured to  connect to nodeos at `http://127.0.0.1:8888/` by default 

so you cal call something like `cleos get info` without needing to specify `-u http://127.0.0.1:3000`


We should improve the readme documentation

**Review by xavier506 — CHANGES_REQUESTED** [review]
Looks good but we should add a readme file explaining what this tool is and  how to use it

**Comment by leisterfrancisco** [comment]
> Looks good but we should add a readme file explaining what this tool is and how to use it

I thought make this in other PR

**Review by xavier506 — APPROVED** [review]
LGTM we can work on readme in separate PR

**Pull request merged**
